service: rs-cart-api
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: admin
  region: eu-west-3
  timeout: 30

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'